[package]
name = "dtekv_emulator"
version = "0.1.0"
edition = "2021"

[lib]
name = "dtekv_emulator"
path = "lib/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.1"
const_format = "0.2.33"
http = "1.1.0"
image = "0.25.5"
tao = "0.30.5"
url = "2.5.3"
wry = "0.46.3"
