pub const INSTRUCTION_ADDRESS_MISALIGNED: u32 = 0;
pub const ILLEGAL_INSTRUCTION: u32 = 2;
pub const ENVIRONMENT_CALL_FROM_M_MODE: u32 = 11;

pub const TIMER_INTERRUPT: u32 = 16;
pub const SWITCH_INTERRUPT: u32 = 17;
pub const BUTTON_INTERRUPT: u32 = 18;

