pub const INSTRUCTION_ADDRESS_MISALIGNED: u32 = 0;
pub const INSTRUCTION_ACCESS_FAULT: u32 = 1;
pub const ILLEGAL_INSTRUCTION: u32 = 2;
pub const BREAKPOINT: u32 = 3;
pub const LOAD_ADDRESS_MISALIGNED: u32 = 4;
pub const LOAD_ACCESS_FAULT: u32 = 5;
pub const STORE_AMO_ADDRESS_MISALIGNED: u32 = 6;
pub const STORE_AMO_ACCESS_FAULT: u32 = 7;
pub const ENVIRONMENT_CALL_FROM_U_MODE: u32 = 8;
pub const ENVIRONMENT_CALL_FROM_S_MODE: u32 = 9;
pub const ENVIRONMENT_CALL_FROM_M_MODE: u32 = 11;
pub const INSTRUCTION_PAGE_FAULT: u32 = 12;
pub const LOAD_PAGE_FAULT: u32 = 13;
pub const STORE_AMO_PAGE_FAULT: u32 = 14;

pub const SWITCH: u32 = 17;
pub const BUTTON: u32 = 18;
